export const GESTURE_CONFIG = {
  extendedFingerAngle: 150,
  foldedFingerAngle: 120,
  extendedTipDistanceRatio: 0.72,
  foldedTipDistanceRatio: 0.58,
  thumbExtendedDistanceRatio: 0.66,
  pinchDistanceRatio: 0.34,
  minimumGestureConfidence: 0.65,
  gestureActivationFrames: 4,
  gestureReleaseFrames: 3,
  weaveMinimumPalmDistanceRatio: 1.2,
  weaveMaximumPalmDistanceRatio: 7,
  weaveMinimumAnchorCount: 4,
  weaveActivationFrames: 5,
  weaveReleaseFrames: 4,
  weaveMinimumConfidence: 0.6,
} as const
