export const WEB_RENDERING = {
  enabled: true,
} as const

export const WEB_CONFIG = {
  shoot: {
    bodyWidthRatio: 0.08,
    controlPointSmoothing: 0.35,
    coreStrandCount: 4,
    crossLinkInterval: 4,
    crossLinkProbability: 0.65,
    headCrossLinkCount: 4,
    headLengthRatio: 0.2,
    headRadialStrandCount: 5,
    headWidthRatio: 0.2,
    launchWidthRatio: 0.05,
    longitudinalSegments: 18,
    maximumCurlAmplitude: 0.055,
    maximumCurlCycles: 2.8,
    maximumLength: 1.5,
    minimumCurlAmplitude: 0.015,
    minimumCurlCycles: 1.2,
    minimumLength: 0.15,
    noiseAmplitude: 0.018,
    originAnchor: 'wrist',
    outerStrandCount: 4,
    projectileLengthRatio: 1.45,
    projectileSpeedRatio: 0.6,
    projectileWidthRatio: 0.48,
    targetDistanceRatio: 7,
    targetSmoothingAlpha: 0.2,
    strandThickness: 2.4,
    taperPower: 0.8,
  },
  weave: {
    maximumAnchorsPerHand: 6,
    minimumCrossHandConnections: 3,
    maximumCrossHandConnections: 10,
    includePalmCentres: true,
    includeSameHandSupportStrands: true,
    anchorLossToleranceFrames: 4,
  },
  geometry: {
    minimumStrandLength: 0.01,
    maximumStrandLength: 2,
    duplicateDistanceThreshold: 0.015,
  },
  rendering: {
    baseThickness: 2,
    baseOpacity: 0.95,
  },
} as const
